credentials:
  usernames:
    admin_user:
      email: admin@example.com
      name: Admin User
      password: <hashed_password>
      role: admin
    backend_user:
      email: backend@example.com
      name: Backend User
      password: <hashed_password>
      role: backend
    customer_user:
      email: customer@example.com
      name: Customer User
      password: <hashed_password>
      role: customer
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
