credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: #####
    rbriggs:
      email: rbriggs@example.com
      name: Rebecca Briggs
      password: #####
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - jsmith@example.com
    - rbriggs@example.com
